### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by peti** [ocramz/matrix-market-attoparsec#3]
Hi,

this packet declares its license as BSD2 in the LICENSE file and in the Cabal file, but the files

- src/Data/Matrix/MatrixMarket.hs
- src/Data/Matrix/MatrixMarket/Internal.hs

say that they're licensed under GPL3, which doesn't mix with the BSD2 in the way it's used here. As it is now, this package must be distributed under GPL3.

Is this situation intentional?

**Comment by ocramz** [comment]
@peti Good catch! It was a sloppy copypaste on my part. The library as a whole is BSD2, I'll fix this asap.

**Comment by ocramz** [comment]
@peti Fixed and updated on Hackage! Thanks for reporting
